[compound_subgraph]
borrow_events="compound_subgraph/borrow_events.graphql"
liquidation_events="compound_subgraph/liquidation_events.graphql"
redeem_events="compound_subgraph/redeem_events.graphql"
repay_events="compound_subgraph/repay_events.graphql"
lending_events="compound_subgraph/lending_events.graphql"
transfer_events="compound_subgraph/transfer_events.graphql"

[aave_v1_subgraph]
borrow_events="aave_v1_subgraph/borrow_events.graphql"
liquidation_events="aave_v1_subgraph/liquidation_events.graphql"
redeem_events="aave_v1_subgraph/redeem_events.graphql"
repay_events="aave_v1_subgraph/repay_events.graphql"
lending_events="aave_v1_subgraph/lending_events.graphql"
usage_as_collateral="aave_v1_subgraph/usage_as_collaterals.graphql"

[aave_v2_subgraph]
borrow_events="aave_v2_subgraph/borrow_events.graphql"
liquidation_events="aave_v2_subgraph/liquidation_events.graphql"
redeem_events="aave_v2_subgraph/redeem_events.graphql"
repay_events="aave_v2_subgraph/repay_events.graphql"
lending_events="aave_v2_subgraph/lending_events.graphql"
usage_as_collateral="aave_v2_subgraph/usage_as_collaterals.graphql"
