[default]
SECRET_NAME_API_KEY="prod/api/keys"
DATA_LAKE_BUCKET_S3 = 's3://data-lakehouse-dev'
AAVE_URL = 'https://api.thegraph.com/subgraphs/name/aave/'
SECRET_NAME = "dev/aave-compound-subgraph/documentdb"
REGION = 'us-east-2'
ALCHEMY_SIMULTANEOUS_CALL_LIMIT = 10
LOG_LEVEL = 'INFO'
START_TIMESTAMP = 1672528451
MAX_TIMEWINDOW_DAYS = 10
NUMBER_OF_THREADS = 5
MONGO_RETRY_WRITE_TO_FALSE="?readPreference=primary&directConnection=true&tls=true&tlsAllowInvalidCertificates=true&tlsAllowInvalidHostnames=true&retryWrites=false"
FEATURE_DB_SECRET_NAME = 'prod/features-db-root'
MAX_WORKERS_PARTITIONS = 15
CURRENT_POSITIONS_MAX_PARALLEL_REQUESTS = 1000

START_TIMESTAMP_AAVE_V1_ETHEREUM = 1578505854
START_TIMESTAMP_AAVE_V2_ETHEREUM = 1606841218
START_TIMESTAMP_AAVE_V2_POLYGON = 1609459200
DOCUMENT_DB_DATABASE = 'ANALYTICS_SUBGRAPH_DEV'
EXTRACTION_PAGINATION_SIZE = 10000
EVENTS_NAMES = ['deposit', 'borrow', 'repay', 'liquidation', 'withdraw']
ACCOUNT_POSITIONS_BLOCK_WINDOW_SIZE = 10

[prod]
DATA_LAKE_BUCKET_S3 = 's3://data-lakehouse-prod'
SECRET_NAME = "prod/documentdb"
ALCHEMY_SIMULTANEOUS_CALL_LIMIT = 50
START_TIMESTAMP_COMPOUND = 1538515557
DOCUMENT_DB_DATABASE = 'ANALYTICS_SUBGRAPH'
